version: '3.7'

networks:
  iam-service:
    driver: bridge

services:
  iam-postgresql:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/auth_data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - iam-service

  iam-service:
    restart: always
    depends_on:
      - iam-postgresql
    env_file:
      - .env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    networks:
      - iam-service
